# Generated by Django 2.2 on 2019-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradedApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pageNumber',
            field=models.IntegerField(default=0),
        ),
    ]
